baseurl = "/" # Hostname (and path) to the root.
title = "Felix Schweigkofler" # Site title.
theme = "coder" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

#disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Felix Schweigkofler" # Author's name.
    info = "MOLECULAR BIOLOGIST" # Author's job title or info.
    description = "Felix Schweigkoflers' personal website" # Site description.
    keywords = "blog,researcher,personal" # Site keywords.
    avatarurl = "images/dna.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "" # Add footer content
    fixedbarContent = "Do you want to know me more private?→" # Add fixedbar content
    fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true  # new add
    enableFacebookShare = true # new add
    enableHatenaShare = true   # new add
    enableLineShare = true     # new add
    enableLinkedInShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links

[[params.social]]
    # If icon is not set, Text is displayed.
    name = "LinkedIn"
    weight = 1
    url = "https://www.linkedin.com/in/felix-Schweigkofler/"

[[params.social]]
    # If icon is not set, Text is displayed.
    name = "founderio"
    weight = 1
    url = "https://www.founderio.com/de/unternehmer/341872"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "about"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "posts"
[[menu.main]]
    name = "Startup"
    weight = 3
    url = "startup"